language: ruby
rvm:
- 2.6
cache: bundler
before_install:
- gem install bundler
bundler_args: "--without development --jobs=3"
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- bin/rails db:migrate RAILS_ENV=test
- bin/rails test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: sqYBDsmbsTubFGi8zs+pTqd39Z5GA+7jK/JwLFQyvNmwg9SnPD/1o3+zda6mCqPluyjTAU2ei3uQJw+e+S4AkxNs7PuqdOencJ5QMGIcp6SvJpUxntbaHqOczmV9Q5Mcn0PZlOvH9MNhlE4cWMOJuXcgpWQRDxxi8viHX/juljB2vNCtBajckyRdGEWhwZLHpBwRFVec0gSz0ZfauQd2JxB2AwULJgSi0A6Lttq4HRKVF1Dvt2HD1RJ4gie5GOXz1UWkWTMHrj1T6CxzQ8NlO7dxfjnfEbOX1FxNKt043JoVPtkdMjij2tyGNgulfj645sak7H0zqN52L3FhRng8AzvoIOkzpbJF3RPtPs1ngkaC5opq/rg8q39pa7DXsRNh1lwOw4GKTfAs+Hn1BAgO9kRiuRI+attPDpnsVePqafSiNXNaV97Vrf7JWwJhWsahQg7eSpNzHRHDf25ahgJnwyA73srTAKk+1ZApXTaHbeqR3b/PNu8vpj6IiUpeT6pSrD0evcmlgc0SMs3qEUcfZPTZpnwC0B1uJwUi1xti8I2QEdyzMqGvd53qkyAFT4FM2ZB3Xgep9pd9CDcXppdGnbtmQU69RD5qC/03K9VCxZLcMUpERlNNNf+C6oGBLRfaHaqnp+gZI64uwzKE+42E1AY8tDJRqrWjw3GNVtZjmSI=
  app: quiet-mesa-90616
  on:
    repo: cat2koban/sample_app
